controllers:
    resource: ../src/Controller/
    type: annotation

witches_beauty_home:
  path: /
  controller: App\Controller\HomeController::home

witches_beauty_product_all:
  path: /All
  controller: App\Controller\ProductController::all

witches_beauty_product_face:
  path: /Face
  controller: App\Controller\ProductController::face

witches_beauty_product_eyes:
  path: /Eyes
  controller: App\Controller\ProductController::eyes

witches_beauty_product_lips:
  path: /Lips
  controller: App\Controller\ProductController::lips

witches_beauty_product_show:
  path: /Show/{id}
  controller: App\Controller\ProductController::show

witches_beauty_about:
  path: /About
  controller: App\Controller\AboutController::about
